ubiquity-os/ubiquity-os-kernel

- src/github/github-context.ts
Resolves #31 
Using the same type setup I've used in https://github.com/ubiquibot/plugin-template
- https://github.com/ubiquity/ubiquibot-kernel/issues/31#issuecomment-2119288902 you don't need the additional stuff I mentioned just the updated context type.
https://github.com/ubiquity/ubiquibot-kernel/assets/106303466/e04d59f7-e720-439a-874a-84440138288b
> fix: union too complex solve

- .github/workflows/build.yml
- .github/workflows/bun-testing.yml
- README.md
- src/github/github-event-handler.ts
- src/github/types/env.ts
- src/worker.ts
- tests/main.test.ts
Resolves #69
- Removed `WEBHOOK_PROXY_URL` which is only for development
- Renamed `PRIVATE_KEY` to `APP_PRIVATE_KEY`
- Tried to set `WEBHOOK_SECRET` as optional but it is required by Octokit
> chore: removed unnecessary secrets

- .github/workflows/build.yml
- .github/workflows/worker-delete.yml
- src/github/types/plugin-configuration.ts
- tests/configuration.test.ts
Resolves #95 
QA: https://github.com/Meniole/conversation-rewards/actions/runs/10609240530 (runs on a branch with depth 4)
> fix: action name regex

- .github/workflows/worker-delete.yml
- src/github/utils/plugins.ts
- tests/configuration.test.ts
Resolves #81
Depends on #97 
QA: https://github.com/Meniole/ubiquibot-kernel/issues/8#issuecomment-2320004355
> fix: read manifest from branch

- src/github/utils/plugins.ts
Addresses https://github.com/ubiquity/ubiquibot-kernel/pull/99#discussion_r1740569764
> chore: refactored empty string

- src/github/handlers/index.ts
Resolves https://github.com/ubiquity/ubiquibot-kernel/issues/105
QA: https://github.com/Meniole/command-start-stop/issues/16
> fix: trimming body to find commands

- package.json
Renamed package scope from `@ubiquity-dao` to `@ubiquity-os`.
> fix: update package name in package.json

- .dev.vars.example
- .github/workflows/worker-deploy.yml
- src/github/types/env.ts
Fixes kernel deployments and runs.
> feat: add environment variable to configuration

- src/github/handlers/push-event.ts
Check for modifications in both config paths in push events.
@0x4007 FYI
> fix(push-event): handle changes to both dev and prod config

- src/github/handlers/push-event.ts
- src/github/utils/plugins.ts
Refine error messages and config path management during push events. The errors were linking to the wrong configuration.
@0x4007 RFC
> fix: enhance error log context and config path handling

- src/github/handlers/push-event.ts
- tests/events.test.ts
Include test case to verify push event handler behavior.
Resolves #147
> test: add unit test for handling push event

- revert-pr-108.txt
This reverts pull request #108
Reverted commit: 975fec50e309e7b8a492123d8b19b646e9199923
> Revert "PR #108"

- .cspell.json
- .github/workflows/worker-deploy.yml
- package.json
> fix: fixed failing worflows

- .github/workflows/worker-deploy.yml
> fix: worker deploy environment

- src/kernel.ts
> fix: illegal invocation

- src/proxy.ts
Rfc @whilefoo the local runs were not working anymore.
> fix: fixed proxy target url

- src/github/handlers/index.ts
- src/github/handlers/issue-comment-created.ts
- src/github/handlers/repository-dispatch.ts
- src/github/types/plugin.ts
- tests/dispatch.test.ts
Resolves https://github.com/ubiquity-os-marketplace/daemon-pricing/issues/69
> fix: unified inputs for worker and action to generate the same payload and signature

- .github/workflows/azure-deploy.yml
Updates Azure deployment script to handle multiple branches.
> chore: update deploy script

- .github/workflows/knip-reporter.yml
Resolves https://github.com/ubiquity/knip-reporter/issues/1
> feat: use ubiquity's knip-reporter

- .github/workflows/deno-deploy.yml
- src/kernel.ts
- tsconfig.json
Resolves https://github.com/ubiquity-os/ubiquity-os-kernel/issues/275
> feat: added Deno deployment
